const $ = id => document.getElementById(id);
const workoutPlans = {
 fullbody:{title:"Full Body Starter",level:"BEGINNER • FULL BODY",description:"A simple 30-minute routine for building consistency and basic strength.",duration:30,calories:180,exercises:[
  {name:"Bodyweight Squats",sets:"3 sets × 12 reps",rest:"60 sec",icon:"🦵",steps:["Stand with feet about shoulder-width apart.","Push your hips back and bend your knees.","Lower with your chest lifted and knees tracking over your feet.","Push through your feet to return to standing."]},
  {name:"Push-ups",sets:"3 sets × 10 reps",rest:"60 sec",icon:"💪",steps:["Place hands slightly wider than shoulder width.","Keep your body in a straight line from head to heels.","Lower your chest with control.","Push the floor away to return to the starting position."]},
  {name:"Glute Bridges",sets:"3 sets × 12 reps",rest:"45 sec",icon:"🍑",steps:["Lie on your back with knees bent and feet flat.","Brace your core and squeeze your glutes.","Lift your hips until your body forms a comfortable straight line.","Lower slowly and repeat."]},
  {name:"Plank",sets:"3 sets × 30 sec",rest:"45 sec",icon:"⏱️",steps:["Place elbows under your shoulders.","Keep your head, hips and heels aligned.","Brace your core and breathe steadily.","Hold without letting your lower back sag."]}]},
 power:{title:"Power Builder",level:"STRENGTH • INTERMEDIATE",description:"A balanced strength routine covering major movement patterns with moderate volume.",duration:45,calories:300,exercises:[
  {name:"Goblet Squat",sets:"3 sets × 10 reps",rest:"75 sec",icon:"🏋️",steps:["Hold a dumbbell or kettlebell close to your chest.","Brace your core and sit your hips down and back.","Keep your knees tracking over your toes.","Drive through your feet to stand tall."]},
  {name:"Dumbbell Row",sets:"3 sets × 10 each side",rest:"60 sec",icon:"💪",steps:["Support one hand on a bench or stable surface.","Keep your back neutral and pull the weight toward your hip.","Pause briefly near the top.","Lower the weight with control."]},
  {name:"Dumbbell Shoulder Press",sets:"3 sets × 10 reps",rest:"75 sec",icon:"🏋️",steps:["Start with weights at shoulder height.","Brace your core and press upward.","Keep the weights controlled and avoid excessive back arching.","Lower to shoulder height and repeat."]},
  {name:"Romanian Deadlift",sets:"3 sets × 10 reps",rest:"75 sec",icon:"🦵",steps:["Stand tall with weights in front of your thighs.","Push your hips back while keeping your spine neutral.","Lower until you feel a comfortable hamstring stretch.","Drive your hips forward to stand."]}]},
 energy:{title:"Energy Burn",level:"CARDIO • BEGINNER FRIENDLY",description:"A 35-minute interval session to make cardio simple, varied and engaging.",duration:35,calories:260,exercises:[
  {name:"Brisk Walk / Easy Jog",sets:"5 min warm-up",rest:"30 sec",icon:"🚶",steps:["Start at an easy pace.","Gradually increase your pace during the final two minutes.","You should be able to speak in short sentences."]},
  {name:"Fast March",sets:"4 rounds × 45 sec",rest:"30 sec",icon:"🏃",steps:["Stand tall and drive your knees upward.","Swing your arms naturally.","Work at a challenging but controlled pace."]},
  {name:"Step-ups",sets:"3 rounds × 60 sec",rest:"45 sec",icon:"⬆️",steps:["Use a stable, low step.","Place your whole foot on the step.","Stand tall, then step down under control.","Alternate your leading leg."]},
  {name:"Easy Walk Cool-down",sets:"5 min",rest:"—",icon:"🧘",steps:["Gradually reduce your pace.","Take slow, comfortable breaths.","Finish with gentle lower-body stretches if comfortable."]}]}
};
let selectedWorkout=null;
function scrollToId(id){$(id).scrollIntoView({behavior:"smooth"});}
function toast(msg){const t=$("toast");t.textContent=msg;t.style.display="block";clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display="none",2200);}
function openWorkout(key){const p=workoutPlans[key];if(!p)return;selectedWorkout=p;$("modalLevel").textContent=p.level;$("modalTitle").textContent=p.title;$("modalDescription").textContent=p.description;$("modalDuration").textContent=p.duration+" min";$("modalCalories").textContent=p.calories;$("modalExerciseCount").textContent=p.exercises.length;$("exerciseList").innerHTML=p.exercises.map((x,i)=>`<article class="exercise"><div class="exercise-number">${String(i+1).padStart(2,"0")}</div><div class="exercise-main"><div class="exercise-heading"><h3>${x.icon} ${x.name}</h3><span>${x.rest} rest</span></div><strong class="sets">${x.sets}</strong><ol>${x.steps.map(s=>`<li>${s}</li>`).join("")}</ol></div></article>`).join("");$("completeWorkoutBtn").onclick=completeSelectedWorkout;$("workoutModal").classList.add("show");$("workoutModal").setAttribute("aria-hidden","false");document.body.classList.add("modal-open");}
function closeWorkout(){$("workoutModal").classList.remove("show");$("workoutModal").setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");}
async function completeSelectedWorkout(){if(!selectedWorkout)return;await logWorkout(selectedWorkout.title,selectedWorkout.duration,selectedWorkout.calories);closeWorkout();setTimeout(()=>scrollToId("dashboard"),250);}
async function loadStats(){try{const s=await fetch("/api/stats").then(r=>r.json());$("statWorkouts").textContent=s.workouts;$("statMinutes").textContent=s.minutes;$("statCalories").textContent=s.calories;$("heroWorkouts").textContent=s.workouts;$("heroMinutes").textContent=s.minutes;$("heroCalories").textContent=s.calories;const rows=await fetch("/api/workouts").then(r=>r.json());$("activity").innerHTML=rows.length?rows.map(x=>`<div class="activity-row"><b>${x.exercise}</b><span>${x.duration} min · ${x.calories} kcal</span></div>`).join(""):"No workouts logged yet — open a plan above to get started.";}catch(e){$("activity").textContent="Demo data unavailable. Start the server to use the API.";}}
async function logWorkout(exercise,duration,calories){try{const r=await fetch("/api/workouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({exercise,duration,calories})});if(r.ok){toast("Workout completed and added to your dashboard ✓");await loadStats();}else toast("Could not save workout");}catch(e){toast("Server connection unavailable");}}
function calculateBMI(){const h=Number($("height").value)/100,w=Number($("weight").value);if(!h||!w){$("bmiResult").textContent="Please enter height and weight.";return}const bmi=w/(h*h);let c=bmi<18.5?"Below typical range":bmi<25?"Typical range":bmi<30?"Above typical range":"Higher range";$("bmiResult").innerHTML=`<strong>BMI: ${bmi.toFixed(1)}</strong> — ${c}. <br><small>Use BMI as a general screening measure, not a diagnosis.</small>`;}
async function getCoach(){const goal=$("goal").value,level=$("level").value;try{const r=await fetch("/api/coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal,level,minutes:30})});const d=await r.json();$("coachResult").innerHTML=`<strong>${d.title}</strong><ul>${d.plan.map(x=>`<li>${x}</li>`).join("")}</ul><small>${d.note}</small>`;}catch(e){$("coachResult").textContent="Start the FitTrack server to use Smart Coach.";}}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeWorkout();});loadStats();
